# vim ft=yaml
# travis-ci.org definition for nipy build
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
language: erlang
env:
    # Enable python 2 and python 3 builds. Python3.2 available in Ubuntu 12.04.
    - PYTHON=python PYSUF=''
    - PYTHON=python3 PYSUF=3 PYVER=3.2
install:
    - sudo apt-get update
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-setuptools
    - sudo apt-get install $PYTHON-nose
    # Installing sympy for python3 needs pip
    # The following is an extended virtual line; will be made into one line by
    # Travis processing.  Avoid `-` at the beginning of the line, remember to
    # add `;` at the end of continuation lines.
    - if [ "${PYSUF}" == "3" ]; then
        sudo easy_install$PYSUF pip;
        sudo pip-$PYVER install sympy;
      else
        sudo apt-get install $PYTHON-sympy ;
      fi
    - sudo easy_install$PYSUF nibabel # Latest pypi
    - $PYTHON setup.py build
    - sudo $PYTHON setup.py install
script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_test
    - cd for_test
    - $PYTHON ../tools/nipnost -A "not slow" `$PYTHON -c "import os; import nipy; print(os.path.dirname(nipy.__file__))"`
